// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU1kwkLQqkeknW-5FZlqUhZ8c-HxS5x00',
    appId: '1:961918859775:web:651033e08ca98ee0530fca',
    messagingSenderId: '961918859775',
    projectId: 'ieu-app0',
    authDomain: 'ieu-app0.firebaseapp.com',
    databaseURL: 'https://ieu-app0-default-rtdb.firebaseio.com',
    storageBucket: 'ieu-app0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1kwkLQqkeknW-5FZlqUhZ8c-HxS5x00',
    appId: '1:961918859775:android:651033e08ca98ee0530fca',
    messagingSenderId: '961918859775',
    projectId: 'ieu-app0',
    databaseURL: 'https://ieu-app0-default-rtdb.firebaseio.com',
    storageBucket: 'ieu-app0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1kwkLQqkeknW-5FZlqUhZ8c-HxS5x00',
    appId: '1:961918859775:ios:651033e08ca98ee0530fca',
    messagingSenderId: '961918859775',
    projectId: 'ieu-app0',
    databaseURL: 'https://ieu-app0-default-rtdb.firebaseio.com',
    storageBucket: 'ieu-app0.firebasestorage.app',
    iosBundleId: 'com.furkankzlsn.ieuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU1kwkLQqkeknW-5FZlqUhZ8c-HxS5x00',
    appId: '1:961918859775:ios:651033e08ca98ee0530fca',
    messagingSenderId: '961918859775',
    projectId: 'ieu-app0',
    databaseURL: 'https://ieu-app0-default-rtdb.firebaseio.com',
    storageBucket: 'ieu-app0.firebasestorage.app',
    iosBundleId: 'com.furkankzlsn.ieuapp',
  );
}
